import { mkdir, writeFile } from "node:fs/promises";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { InMemoryTransport } from "@modelcontextprotocol/sdk/inMemory.js";
import { SERVER_NAME, SERVER_VERSION, buildServer } from "../src/server.js";

interface JsonSchemaProp {
  type?: string | string[];
  description?: string;
  default?: unknown;
  enum?: unknown[];
}
interface JsonSchema {
  properties?: Record<string, JsonSchemaProp>;
  required?: string[];
}

function renderType(prop: JsonSchemaProp): string {
  if (prop.enum) return prop.enum.map((value) => `\`${JSON.stringify(value)}\``).join(" \\| ");
  if (Array.isArray(prop.type)) return prop.type.join(" \\| ");
  return prop.type ?? "object";
}

function cell(text: string): string {
  return text.replace(/\|/g, "\\|").replace(/\n+/g, " ").trim();
}

async function main(): Promise<void> {
  const [clientTransport, serverTransport] = InMemoryTransport.createLinkedPair();
  const server = buildServer();
  await server.connect(serverTransport);
  const client = new Client({ name: "docgen", version: "0.0.0" });
  await client.connect(clientTransport);
  const { tools } = await client.listTools();
  await client.close();
  await server.close();

  const sorted = [...tools].sort((a, b) => a.name.localeCompare(b.name));
  const out: string[] = [
    "<!-- GENERATED by scripts/gen-tools-doc.ts — do not edit by hand. Regenerate: npm run docs:tools -->",
    "",
    `# Tool reference — ${SERVER_NAME} v${SERVER_VERSION}`,
    "",
    `The agent drives these ${tools.length} MCP tools. Auto-generated from the live server's \`tools/list\`.`,
    "",
  ];

  for (const tool of sorted) {
    out.push(`## \`${tool.name}\``, "");
    if (tool.description) out.push(cell(tool.description), "");
    const schema = tool.inputSchema as JsonSchema;
    const props = schema.properties ?? {};
    const names = Object.keys(props);
    if (names.length === 0) {
      out.push("_No parameters._", "");
      continue;
    }
    const required = new Set(schema.required ?? []);
    out.push("| Param | Type | Required | Default | Description |", "|---|---|---|---|---|");
    for (const name of names) {
      const prop = props[name] as JsonSchemaProp;
      const def = prop.default !== undefined ? `\`${JSON.stringify(prop.default)}\`` : "";
      out.push(
        `| \`${name}\` | ${renderType(prop)} | ${required.has(name) ? "yes" : "no"} | ${def} | ${cell(prop.description ?? "")} |`,
      );
    }
    out.push("");
  }

  await mkdir("docs", { recursive: true });
  await writeFile("docs/TOOLS.md", `${out.join("\n")}\n`);
  console.log(`wrote docs/TOOLS.md (${tools.length} tools)`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
